### ISSUE TITLE
Allow binding large immediate values to instructions

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/cranelift#1052]
This is closely related to #1027 and #1012 but applies to large values (e.g. 128-bit) that currently have a level of indirection (see uses `Constant` and `Immediate` entities). In `legalize.rs`, we currently do:
```
def!(b = f64const(ieee64_zero)), // zero out a different XMM register; the shuffle mask for moving the lowest byte to all other byte lanes is 0x0
def!(c = bitcast_f64_to_any8x16(b)), // no instruction emitted; informs the SSA that the 0 in b can be used as a vector of this type
```

But we should be doing the much more clear:
```
def!(c = vconst(v128_zero)), // legalized to a PXOR
```

The literal `v128_zero`, however, cannot be created with `Literal::constant` as other literals are because there is no way to access the `DataFlowGraph` to inform it that a new large constant or immediate is needed. Some change is needed in order for `v128_zero` to be created but it is not clear to me exactly what.

This may be highlighting an API weirdness: the `Constant/Immediate` entity indirection to a collection stored on the `DataFlowGraph` is necessary to keep the `InstructionData` size under 16 bytes. But perhaps there is another way around this using clever slices and lifetimes.

**Comment by bnjbvr** [comment]
> This may be highlighting an API weirdness

Agreed, I've always felt something was rather strange with this API. In particular, having the parser create stuff in the DFG seems weird. It shows that the end user of Constant/Immediate needs to do two things at once when they want to use it.

One idea: the InstBuilder trait inherits the InstBuilderBase which contains the `data_flow_graph()` method, effectively returning the DFG. So InstBuilder could instead take the Constant/Immediate, insert it in the dfg, and use the returned handle within the instruction it generates. It would either require more knowledge in the meta-crate to learn how to do this kind of things, or require something like the ability to augment the InstBuilder (e.g. #921).
