### ISSUE TITLE
Live ranges: remove the cmp! macro

### ISSUE THREAD

**Issue by bnjbvr** [bytecodealliance/cranelift#1072]
#1045 introduces a new macro to make comparisons of live ranges easier, according to the ProgramOrder ordering them. This was done to make it easier to read things like "order.cmp(a, b) != Ordering::Less", which means "a is greater or equal than b". The need to invert the meaning makes it hard to grasp what it's doing, and I thought using plain < / > signs made it simpler.

@abrown suggested:

> What about just implementing Ord and Eq on ProgramOrder or ExpandedProgramPoint or wherever it is needed so that the <, <=, >, etc. are overloaded and we can just use the operators directly instead of a macro or order.cmp...? It may require adding a method to ProgramOrder but the following seems more clear to me: order.of(to) >= order.of(self.def_begin).

While the former can't be done (since the ProgramOrder uses its own data fields to retrieve the actual position index used in the comparison), the latter with an "order.of" function can be done. See [here](https://github.com/bnjbvr/cranelift/commit/0b8e633314fac9d607a47a1955f9832a250a2319) for an incomplete implementation.

### Alternatives

- just using the previous state. This would be worse in my opinion, and doesn't solve the readability issue.
- keeping the cmp! macro and extending usage. It's a simple macro, but that's one more step when trying to understand this code, and debugging with macros isn't trivial.

**Comment by lars-t-hansen** [comment]
The one question I have about `order.of` is that unlike cmp, you can compute `order.of(x)` and `order.of(y)` at different times (by accident or on purpose); are the values returned by these functions sensitive to what might happen inbetween the calls?  I suspect the answer is yes, eg, appending an instruction may trigger a renumbering.

Not sure it's a problem, exactly, provided it's reasonably documented.

**Comment by bnjbvr** [comment]
> The one question I have about order.of is that unlike cmp, you can compute order.of(x) and order.of(y) at different times (by accident or on purpose); are the values returned by these functions sensitive to what might happen inbetween the calls? I suspect the answer is yes, eg, appending an instruction may trigger a renumbering.

Good point. As far as I see, `order.of` is always called in pairs (for the two elements we want to compare) and directly consumed (so no inbetween calls effectively happen). Grouping the order computations (as is done with the current macro, or with the previous way it was done) prevents that issue from ever happening.

Also, using the macro effectively hides the type of the measure used to compare values. In the test implementation, it's a usize, while it's a u32 for the layout implementation of the trait. It might be better for encapsulation.

I don't have a strong opinion here overall. It seems keeping the macro (and maybe extending its usage) would be good enough at the moment.

**Comment by bnjbvr** [comment]
It's a tiny detail, and it doesn't cause much trouble since it's nicely enclosed, so closing this issue for now.
