### ISSUE TITLE
Merge SIMD and scalar WASM-to-CLIF translation

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/cranelift#1139]
In `code_translator.rs`, @bnjbvr noted (https://github.com/CraneStation/cranelift/pull/1104#discussion_r333981863) that the boolean logical operator CLIF is identical between the scalar code and the SIMD code; e.g., `let (a, b) = state.pop2(); state.push1(builder.ins().bor(a, b));`. This code duplication can be removed by merging the match of some SIMD and scalar operators (the logical ones for sure, but perhaps there are others).

**Comment by ash-tamraz** [comment]
If this isn't way beyond my ability level at the moment, I'd be interested in working on this. How difficult would you guesstimate this to be?

**Comment by abrown** [comment]
It shouldn't be too bad as it was mainly a style suggestion by @bnjbvr: e.g., if you compare the translation of scalar `xor` (https://github.com/CraneStation/cranelift/blob/master/cranelift-wasm/src/code_translator.rs#L797-L800) and vector `xor` (https://github.com/CraneStation/cranelift/blob/master/cranelift-wasm/src/code_translator.rs#L1113-L1116) they are pretty much the same. To close this issue, I would expect we would want to find instances where this is the case (maybe it's just the bitwise operators?) and merge them with their scalar version above, e.g., `Operator::I32Xor | Operator::I64Xor | Operator::V128Xor => ...`. Any vector translations with bitcasts in them should be avoided, I think, until we figure out https://github.com/CraneStation/cranelift/issues/1192.

**Comment by bnjbvr** [comment]
Indeed, this is mostly code motion in the wasm translator as @abrown showed.
