### ISSUE TITLE
can't compile anymore with cargo build when offline

### ISSUE THREAD

**Issue by stefson** [bytecodealliance/cranelift#1210]
hey there, I just noticed that the most recent version of 0.49.0 (https://github.com/CraneStation/cranelift/commit/79dcbb138e51372faefa9ac6eaf0fee3901366b7) doesn't build, unless there's an internet connection and the user is allowed to access some server at `gimli-rs`

I haven't yet found out where this was introduced, and why. But I would like to point out that this is a very distro unfriendly behavior, making the job of packaging cranelift difficult or impossible, depending on how strict the individual distro's policies are in regard of network sandboxing for root. 

Also I think firefox pulls in certain parts of your tree, so this might blow up at their end too.

**Comment by bjorn3** [comment]
That is https://github.com/CraneStation/cranelift/pull/1206. `faerie` accidentially released a patch version which bumped the `target-lexicon` version. However `target-lexicon` is a public dependency, so we had to update `target-lexicon` to that version too. `object` didn't want to release a new version, until some more changes are made, so we had to use the git version. Once `object` gets a new version released, we will switch back to the crates.io version.

> Also I think firefox pulls in certain parts of your tree, so this might blow up at their end too.

The author of the mentioned PR works at Mozilla ;)

**Comment by sunfishcode** [comment]
That git dependency would break crates.io publishing too. The only reason we didn't notice yet is that we haven't added cranelift-object to the publish script yet, so we aren't publishing it on crates.io yet. But we really should publish it :-).

**Comment by stefson** [comment]
uhm, so there's going to be a v0.49.1 soon?

**Comment by sunfishcode** [comment]
The 0.49.0 packages which are published on crates.io are ok. There isn't a published cranelift-object yet. We could probably start publishing it soon, once this issue is resolved.

**Comment by bnjbvr** [comment]
It's been a while and `object` hasn't been updated and published... Any chance we could reprioritize publishing a new version of `object`, please, @philipc / @fitzgen ?

**Comment by philipc** [comment]
Sure, I can do it tomorrow. I was waiting for https://github.com/bytecodealliance/target-lexicon/pull/35, which looks like it is done and just needs to be merged/published.

**Comment by philipc** [comment]
`object` 0.16.0 is published.

That's not going to fix cranelift 0.49.0 by itself though, there'll need to be 0.50.0. @stefson Is there a reason you are obtaining cranelift from git instead of using the published versions on crates.io?

**Comment by stefson** [comment]
This seems to be fixed in git now, do you think you could add a point release?

**Comment by bjorn3** [comment]
`object` is a public dependency, so updating it is a breaking change.

**Comment by philipc** [comment]
`cranelift-object` hasn't actually been published yet though, so not sure we care about breaking changes for it. And that's also why I don't understand why using a git version of `object` was an issue. distros shouldn't be compiling `cranelift-object` because it hasn't been published. gentoo could add a patch to delete `cranelift-object` from the root Cargo.toml in the 0.49.0 release if they must use the git source for cranelift, but obtaining cranelift from crates.io would also fix this.

**Comment by stefson** [comment]
fixed in v0.52.0
