### ISSUE TITLE
Verifier(?) bug in divert-heavy function

### ISSUE THREAD

**Issue by iximeow** [bytecodealliance/cranelift#1219]
First, some clif:
```
; guest_func_73448
function u0:73448(i64 vmctx, i32, i32) -> i32 system_v {
    gv0 = vmctx
    heap0 = static gv0, min 0x0052_0000, bound 0x0052_0000, offset_guard 0x0040_0000, index_type i32 

                                ebb0(v0: i64, v1: i32, v2: i32):
                                    v14 -> v1
                                    v22 -> v2
@15eb1d7                            v12 = iconst.i32 0
@15eb1db                            v13 = iconst.i32 0
@15eb1df                            jump ebb11(v12, v13)

                                ebb11(v25: i32, v110: i32):
@15eb2c3                            v102 = iconst.i32 12
@15eb2c5                            v103 = sdiv v110, v102
@15eb2ce                            brnz v25, ebb2
@15eb2d4                            brnz v110, ebb13
@15eb2d8                            v108 = iconst.i32 4
@15eb2da                            v109 = iadd v25, v108
@15eb2df                            v111 = iconst.i32 1
@15eb2e1                            v112 = iadd v110, v111
@15eb2e6                            v113 = heap_addr.i64 heap0, v22, 1
@15eb2e6                            v114 = load.i32 v113+4
@15eb2e9                            v115 = icmp sge v112, v114
@15eb2e9                            v116 = bint.i32 v115
@15eb2ea                            brnz v116, ebb10(v14)
@15eb2ec                            jump ebb11(v109, v112)

                                ebb13:
@15eb30b                            trap unreachable

                                ebb10(v121: i32):
@15eb315                            return v121

                                ebb2:
@15eb3fd                            trap unreachable
}
```
(EDIT: Missed the closing `}` in this clif at first!)

when built through clif-util, like: `./target/debug/clif-util compile --target x86_64 -D the_file.clif`, this produces a verifier error as a result of what looks like a regalloc bug.

`clif-util`'s output, including the reported error:

```
     Running `target/debug/clif-util compile --target x86_64 -D ../yosys-lucetc-issue_0.4.1_guest_func_73448.clif`
function u0:73448(i64 vmctx [%rdi], i32 [%rsi], i32 [%rdx]) -> i32 [%rax] system_v {
    gv0 = vmctx
    heap0 = static gv0, min 0x0052_0000, bound 0x0052_0000, offset_guard 0x0040_0000, index_type i32 

                                ebb0(v0: i64 [%rdi], v1: i32 [%rsi], v2: i32 [%rdx]):
                                    v126 -> v0
                                    v14 -> v1
                                    v22 -> v2
@15eb1d7 [RexOp1pu_id#b8,%rax]      v12 = iconst.i32 0
@15eb1db [RexOp1pu_id#b8,%rcx]      v13 = iconst.i32 0
@15eb1df [Op1jmpb#eb]               jump ebb11(v12, v13)

                                ebb11(v25: i32 [%rax], v110: i32 [%rcx]):
@15eb2c3 [RexOp1pu_id#b8,%rbx]      v102 = iconst.i32 12
@15eb2c5 [RexOp1umr#89,%r8]         v127 = copy v110
@15eb2c5 [RexOp1r_ib#70c1,%r8]      v122 = sshr_imm v127, 31
@15eb2c5 [RexOp1umr#89,%r9]         v128 = copy v110
@15eb2c5 [RexOp1rmov#89]            regmove.i32 v2, %rdx -> %r10
@15eb2c5 [RexOp1rmov#89]            regmove v122, %r8 -> %rdx
@15eb2c5 [RexOp1rmov#89]            regmove.i32 v2, %r10 -> %r8 
@15eb2c5 [RexOp1rmov#89]            regmove v25, %rax -> %r10
@15eb2c5 [RexOp1rmov#89]            regmove v128, %r9 -> %rax
@15eb2c5 [RexOp1rmov#89]            regmove v25, %r10 -> %r9 
@15eb2c5 [RexOp1div#70f7,%rax,%rdx] v103, v123 = x86_sdivmodx v128, v122, v102
@15eb2ce [RexOp1tjccb#75]           brnz v25, ebb2
@15eb2d4 [RexOp1tjccb#75]           brnz v110, ebb13
@15eb2d8 [RexOp1pu_id#b8,%rax]      v108 = iconst.i32 4
@15eb2da [RexOp1rmov#89]            regmove v25, %r9 -> %rbx
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
; error: inst37: inconsistent with global location %rax (regmove.i32 v25, %9 -> %3) 

@15eb2da [RexOp1rr#01,%rbx]         v109 = iadd v25, v108
@15eb2df [RexOp1pu_id#b8,%rax]      v111 = iconst.i32 1
@15eb2e1 [RexOp1rr#01,%rcx]         v112 = iadd v110, v111
@15eb2e6 [RexOp1icscc_id#7081,%rax] v124 = icmp_imm.i32 uge v2, 0x0051_fffe
@15eb2e6 [RexOp1rmov#89]            regmove.i32 v2, %r8 -> %rdx
@15eb2e6 [RexOp1t8jccb#74]          brz v124, ebb15
@15eb2e6 [Op1jmpb#eb]               jump ebb14

                                ebb14:
@15eb2e6 [Op2trap#40b]              trap heap_oob

                                ebb15:
@15eb2e6 [RexOp1umr#89,%rax]        v125 = uextend.i64 v2
@15eb2e6 [RexOp1umr#8089,%r8]       v129 = copy.i64 v0
@15eb2e6 [RexOp1rr#8001,%r8]        v113 = iadd v129, v125
@15eb2e6 [RexOp1ldDisp8#8b,%rax]    v114 = load.i32 v113+4
@15eb2e9 [RexOp1icscc#39,%rax]      v115 = icmp.i32 sge v112, v114
@15eb2e9 [RexOp2urm_noflags#4b6,%rax] v116 = bint.i32 v115
@15eb2ea [RexOp1tjccb#75]           brnz v116, ebb10(v1)
@15eb2ec [RexOp1rmov#89]            regmove.i32 v109, %rbx -> %rax
@15eb2ec [Op1jmpb#eb]               jump ebb11(v109, v112)

                                ebb13:
@15eb30b [Op2trap#40b]              trap unreachable

                                ebb10(v121: i32 [%rsi]):
@15eb315 [RexOp1rmov#89]            regmove v121, %rsi -> %rax
@15eb315 [Op1ret#c3]                return v121

                                ebb2:
@15eb3fd [Op2trap#40b]              trap unreachable
}

; 1 verifier error detected (see above). Compilation aborted.
```

This is a minimization of a bug reported in lucet, https://github.com/fastly/lucet/issues/361 - I've only tried this with a few cranelift versions (0.46.1, 0.43.0, plus another older one which I don't recall).

The important pieces here are, I think, the `sdivmulx` on a basic block parameter, which is fairly constrained and forces several values to move around, and a subsequent regmove:
```
@15eb2da [RexOp1rmov#89]            regmove v25, %r9 -> %rbx
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
; error: inst37: inconsistent with global location %rax (regmove.i32 v25, %9 -> %3) 
```
It looks like the verifier is expecting `v25` to end up in `rax` after the last assignment in the basic block, but it's in `rbx` instead, resulting in the error.

**Comment by iximeow** [comment]
assigned myself because I'd like to look into this, it seems a little like an issue I've caused myself before, where I neglected to check if a value was diverted.

If someone else is interested and I haven't figured this out today, please chime in! I probably won't have time to investigate in the remainder of the week.

**Comment by iximeow** [comment]
Updated the title to reflect my current theory: `RegDiversions` when the verifier visits the "invalid" instruction is in fact empty, but I believe it should contain _at the least_ a diversion of `v25` from `rax` to `r9`,

* `regmove v25, %r9 -> %rbx` is after a branch, and has a unique predecessor, we so [remove diversions for values not live through the target](https://github.com/CraneStation/cranelift/blob/master/cranelift-codegen/src/verifier/locations.rs#L335-L339)
  - this seems excessive, since local values may be diverted through a branch to a basic block they aren't live in?
* since the set of diversions through the branch is now empty, checking for a diverted v25 [turns up None](https://github.com/CraneStation/cranelift/blob/master/cranelift-codegen/src/verifier/locations.rs#L282), and the verifier falls back to checking against the globally allocated register (rax), and errors.

It seems like the set of diversions the branch target is checked against should be derived from but not mutate the diversions in the current EBB. Something like replacing the current [`val_to_remove`](https://github.com/CraneStation/cranelift/blob/master/cranelift-codegen/src/verifier/locations.rs#L337-L339) list like:
```
...
    if lr.is_livein(ebb, &self.func.layout) {
        val_to_add.push(value)
    } else if ...
...
if is_after_branch && unique_predecessor {
     // I don't know how to build a RegDiversions. Pretend this does that.
    let dest_diverts = val_to_add.collect();
    debug_assert!(divert.check_ebb_entry(&self.func.entry_diversions, ebb));
}
```
seems like it should be correct, but I haven't looked at the verifier before today and this isn't entirely where I expected to end up. A second opinion would be greatly appreciated.

I'll keep an eye on this PR and if the above seems sound I can try putting together a patch, but it probably won't happen this week.

**Comment by bnjbvr** [comment]
Thanks for opening an issue. The lucet issue mentions that you've tried this with BB form and that it reproduced too. Any chance we could get a minified test case in BB form, please? I've tried using the wasm command on the original test case on Cranelift master and didn't get into this verifier error.

**Comment by iximeow** [comment]
As far as reproducing with `clif-util wasm` from the original .wasm, it in fact does not occur on master. I bisected that to commit `decec8b` to be sure, which is where basic blocks became the default. The verifier error is only found and reported with `--set enable_verifier` (not by passing -c! this surprised me.)

For my comment on the lucet issue, I now think I misread the commit history and reversed order on the commits I'd been looking at, getting the relation to `decec8b` backwards. For that matter, my commit message in the commit I referenced in the lucet issue was obviously wrong, `yosys-lucetc-issue_0.4.1_guest_func_73448.clif` is definitively _not_ in basic block form. I have no idea why I thought otherwise.

The version I did _not_ see a verifier error in, `yosys-lucetc-issue_guest_func_73448.clif`, _is_ in basic block form. The lack of error there is why I didn't bother reducing that case.

I did double check that the clif I included with the issue at the top _does_ yield a verifier error still on master, so at least that still checks out...

**Comment by iximeow** [comment]
I really haven't kept up on our EBB/BB work - from the code I pointed out above and the clif in OP, I do think this error only comes up with EBBs. Are we still maintaining EBB-related parts, or is the answer "just don't use EBBs"?

**Comment by bnjbvr** [comment]
Our current thinking is that we should get rid of EBBs once and for all, once some fuzzing has proven it doesn't break everything everywhere.

**Comment by iximeow** [comment]
Basic blocks are no longer optional, so this error is no longer reachable.
