### ISSUE TITLE
uextend.i128 instead of iconcat fails run test

### ISSUE THREAD

**Issue by krk** [bytecodealliance/cranelift#1230]
In #1229, when instead of `iconcat`, `uextend` is used at https://github.com/bytecodealliance/cranelift/pull/1229/commits/596b87343155355e36ae8c7e40992509a5a1c59d#diff-63af3d6bea89b7f31ef4569ff5a67c0dR7 run test fails with a `Verifier errors` without further details.

```diff
-v1 = iconcat v0, v0
+v1 = uextend.i128 v0
```

To my understanding, test should pass with either instruction.

**Comment by krk** [comment]
Detailed error message can be seen with changing line https://github.com/bytecodealliance/cranelift/blob/047e1eed82080299ed160344d2ee11a4af2de8eb/cranelift-codegen/src/result.rs#L15 with `#[error("Verifier errors: \n{0}")]`.

```
Verifier errors: 
- inst5: v4 is a real GPR value defined by a ghost instruction
```

**Comment by krk** [comment]
Culprit seems to be the `isplit` instruction, minimal test case:

```rust
test run
target x86_64

function %isplit_bug() -> b1 {
ebb0:
    v0 = iconst.i16 0
    v1, v2 = isplit.i16 v0
    v3 = iconst.i8 0
    v4 = icmp eq v1, v3
    return v4
}
; run
```

output:

```rust
 ERROR cranelift_filetests::concurrent    > FAIL: run(%isplit_bug):
Verifier errors: 
- inst1: v1 is a real GPR value defined by a ghost instruction

FAIL filetests/isa/x86/isplit_bug.clif: run(%isplit_bug):
Verifier errors: 
- inst1: v1 is a real GPR value defined by a ghost instruction

1 tests
1 failure
```

**Comment by bnjbvr** [comment]
The `real GPR value defined by a ghost instruction` error message should be enhanced; what it says is that there's no machine encoding for a given Cranelift instruction. In this case, in comment 0, it's `uextend.i128` (or what it's legalized to) which has no encodings. And for good reason: we don't have machine encodings for i128 instructions, hence the need to legalize, in which `isplit` and `iconcat` play a big role. In the last comment, it's `isplit`, which should only be used hands in hands with iconcat to split values from one to two registers (and conversely).

We might need better documentation to explain the differences between `uextend` (= creates a real machine instruction) and `isplit`/`iconcat` (= useful only during compilation, should only appear at control flow/function boundaries once legalization happened).
