### ISSUE TITLE
Chat platform uses old name

### ISSUE THREAD

**Issue by XAMPPRocky** [bytecodealliance/cranelift#1239]
I'm not sure if this is the right place for this issue, but there isn't a general bytecodealliance repo. The current official platform is still `Cranestation/Lobby` on gitter.im. Is there plans to change the name or move to a different platform with the organisational change?

Personally the gitter clients has gotten quite poor in terms of performance and responsiveness, and I would prefer if there was a general organisation for all of the projects under the umbrella as the current gitter is mainly focused only on cranelift.

**Comment by sunfishcode** [comment]
Agreed. We're currently continuing to use gitter and `CraneStation` (as well as #cranelift on irc.mozilla.org), but this is now just an interim solution until we make a new plan.

One possible plan is to wait for Mozilla to announce their plan for replacing irc.mozilla.org, and set something up with the same service. The Bytecode Alliance isn't specific to Mozilla, but for people who also hang out on Mozilla channels, it's convenient to reduce the number of different chat services to deal with.

**Comment by XAMPPRocky** [comment]
If could I make a suggestion of a platform, we have been using Zulip in the Rust lang organisation, and I have found the experience overall very positive. https://zulipchat.com

**Comment by bjorn3** [comment]
Zulip forces you to make your email public, which is something I don't like.

**Comment by XAMPPRocky** [comment]
@bjorn3 While I can understand the want for anonymity, the more anonymous you allow your users to be, the more difficult it will be to moderate the platform. Which will put more work on the people you actually want to use your platform.

**Comment by bjorn3** [comment]
I am fine with any platform for which I can see messages without login **and** for which I don't have to expose my email to other users. I am fine with exposing my github name though.

**Comment by bjorn3** [comment]
Also I did create a Zulip account once, but it never told me that my email would be exposed. I only noticed it once I was exploring the UI. After I noticed I immediately removed my account.

**Comment by XAMPPRocky** [comment]
One thing that might be important for some is that Zulip allows you to import from Gitter, so you can retain all of the previous discussion. https://zulipchat.com/help/import-from-gitter

**Comment by XAMPPRocky** [comment]
As an update: [Mozilla has chosen to use Matrix](https://matrix.org/blog/2019/12/19/welcoming-mozilla-to-matrix/).

**Comment by bnjbvr** [comment]
Closing: we'll be using Zulip. See README/CONTRIBUTING. Thanks for opening an issue, though!
