### ISSUE TITLE
How do I use cranelift-object as a backend for PE/COFF?

### ISSUE THREAD

**Issue by jyn514** [bytecodealliance/cranelift#1254]
Is there a supported way currently to use `cranelift-object` as a backend for `cranelift-module`? If not, could you release it to crates.io so other projects outside the cranelift umbrella can use it?

I'm interested supporting Windows in my compiler, which, since I'm emitting native code, means I need to emit PE/COFF object files. `cranelift-faerie` does not currently support this (https://github.com/m4b/faerie/issues/46). It's mentioned in https://github.com/bytecodealliance/cranelift/issues/511 that `cranelift-object` supports COFF, so I was planning to use that. However, I can't figure out how! `cranelift-object` isn't on either docs.rs or crates.io, and I can't find any project using it except https://github.com/bytecodealliance/lucet/, which pulls it directly from GitHub.

**Comment by bjorn3** [comment]
`cranelift-object` is currently stuck on a git version of `object`, so it can't be uploaded to crates.io.

**Comment by jyn514** [comment]
Why is it using a git version? Is there a feature of `object` that hasn't been released or has no one gotten around to changing it?

**Comment by jyn514** [comment]
I tried updating it to 0.16.0 only and it seemed to work, I can make a PR

**Comment by bjorn3** [comment]
https://github.com/bytecodealliance/cranelift/pull/1206

object didn't update to target-lexicon 0.9 yet. Not sure if it has now.

**Comment by jyn514** [comment]
They seem to have updated since: https://github.com/gimli-rs/object/blob/master/Cargo.toml#L17

**Comment by philipc** [comment]
The problem was `object` was updated, but not published. It is published now (0.16.0).

**Comment by jyn514** [comment]
I think this is just waiting on a new release of cranelift.
