### ISSUE TITLE
Remove duplicate dependencies

### ISSUE THREAD

**Issue by jyn514** [bytecodealliance/cranelift#1256]
- What is the feature or code improvement you would like to do in Cranelift?

Remove duplicate versions of `quote`, `syn`, and `xid-tools`.
As you can see in the dependency tree below, extremely old versions of these are required by `packed_struct_codegen`.

<details><summary>Dependency tree (generated with `cargo tree -d`):</summary>

```
quote v0.3.15
├── packed_struct_codegen v0.3.0
│   └── cranelift-codegen-shared v0.51.0 (/home/joshua/Documents/Programming/rust/cranelift/c
ranelift-codegen/shared)
...snip...

quote v1.0.2
├── failure_derive v0.1.6
│   ├── failure v0.1.6
│   │   ├── cranelift-faerie v0.51.0 (/home/joshua/Documents/Programming/rust/cranelift/crane
lift-faerie)
...snip...

syn v0.11.11
└── packed_struct_codegen v0.3.0
    └── cranelift-codegen-shared v0.51.0 (/home/joshua/Documents/Programming/rust/cranelift/c
ranelift-codegen/shared)
...snip...

syn v1.0.8
├── failure_derive v0.1.6
│   ├── failure v0.1.6
│   │   ├── cranelift-faerie v0.51.0 (/home/joshua/Documents/Programming/rust/cranelift/cranelift-faerie)
...snip...

unicode-xid v0.0.4
├── syn v0.11.11
│   └── packed_struct_codegen v0.3.0
│       └── cranelift-codegen-shared v0.51.0 (/home/joshua/Documents/Programming/rust/craneli
ft/cranelift-codegen/shared)
...snip...

unicode-xid v0.2.0
├── proc-macro2 v1.0.6
│   ├── failure_derive v0.1.6
│   │   ├── failure v0.1.6
│   │   │   ├── cranelift-faerie v0.51.0 (/home/joshua/Documents/Programming/rust/cranelift
... snip ...
```

</details>

- What is the value of adding this in Cranelift?

Reduced compile times. Also removes warnings from `rustdoc` about duplicated output directories.

- Do you have an implementation plan?

Unfortunately since there is no version of `packed_struct_codegen` later than `0.3`, there's not an easy way to fix this. Cranelift would probably have to nudge that project or switch to a different library like https://docs.rs/bitflags/.

- Have you considered alternative implementations? If so, how are they better
  or worse than your proposal?

Cranelift could just leave the duplicates in place. That would be easy to do but also requires 2 versions of syn and quote to be compiled for every newcomer and CI run.

**Comment by bnjbvr** [comment]
It's indeed unfortunate to have duplicated dependencies. Any chance we could do this work upstream and have the maintainers bump a new version of this crate?

cc @sstangl @abrown

**Comment by abrown** [comment]
I don't think the bitflags library will work in this case so I guess the upstream update is the way to go. We could alternately remove packed_struct altogether since it was an ease-of-use decision for `EncodingBits` and it seems to cause `no_std` issues (e.g. #1262)... but I think I would lean towards the upstream update since the use of packed_struct makes the code more explicit and less error-prone. @sstangl, what do you think?

**Comment by bnjbvr** [comment]
Now that https://github.com/bytecodealliance/cranelift/pull/1282 has landed, we don't use packed_struct anymore, and `cargo tree -d` doesn't show anything. Closing, but feel free to reopen if I misunderstood anything.

**Comment by jyn514** [comment]
Looks great to me, thanks for working on this!
