### ISSUE TITLE
Should R32 and R64 be combined to a single Ref type?

### ISSUE THREAD

**Issue by eqrion** [bytecodealliance/cranelift#1267]
I'm looking at reftypes integration in CL/SM. One slight papercut is having to determine the pointer size in all IR emission points to emit the appropriate `Rxy` type.

Is it a reasonable expectation that embedders will only ever need pointer sized references? What would be the use of a non-pointer sized reference? And if it's not needed, could we replace `R32` and `R64` with a single assumed target pointer-sized `Ref` type?

**Comment by bjorn3** [comment]
1. What should `Type::bytes` return.
2. For normal pointers (represented using `I*`) you already need to know the native pointer size anyway.
3. Every heard about the `x86_64-linux-gnu-x32` target? It uses 32bit pointers, despite using a 64bit arch to save pointer space.

**Comment by eqrion** [comment]
>     1. What should `Type::bytes` return.
> 

Ah, that's a bit inconvenient. We would need the `TargetIsa` to determine the size. That's probably reason enough to leave it as R32/R64.

>     2. For normal pointers (represented using `I*`) you already need to know the native pointer size anyway.
> 

Yes that is true, however there is use for 32bit integers on a 64bit target, and 64bit integers on a 32bit target. I don't think there is use for a 32bit reference on a 64bit target, or a 64bit reference on a 32bit target.

>     3. Every heard about the `x86_64-linux-gnu-x32` target? It uses 32bit pointers, despite using a 64bit arch to save pointer space.

I have heard of this, but I assumed it could treated as a 32bit target. I had also heard that it might be being deprecated.

Overall, it's just a papercut in IR emission and if it makes later stages more complicated because it doesn't encode the byte size then I'd say it's not worth it.

**Comment by bjorn3** [comment]
> I have heard of this, but I assumed it could treated as a 32bit target.

Cranelift only looks at the `x86_64` part, except for `isa.default_call_conv()`.

> Overall, it's just a papercut in IR emission and if it makes later stages more complicated because it doesn't encode the byte size then I'd say it's not worth it.

Maybe add a `isa.reference_type()` counterpart to `isa.pointer_type()`

**Comment by eqrion** [comment]
Closing this as I don't think there's anything actionable.
