### ISSUE TITLE
How do I use get_libcall_funcref?

### ISSUE THREAD

**Issue by jyn514** [bytecodealliance/cranelift#1273]
I'm looking at the documentation for https://docs.rs/cranelift-codegen/0.51.0/cranelift_codegen/ir/fn.get_libcall_funcref.html and I'm not sure how to get an `Inst` to pass to it. It looks like `Inst` is returned by `InstBuilder.call`, but that requires me to have a `FuncRef` with the same signature already. Am I missing something obvious? It would seem to make more sense to have it take a `Signature` ...

Context: I'm trying to call `memcpy` from libc to fix https://github.com/jyn514/rcc/issues/71.

**Comment by bjorn3** [comment]
You could use [`FunctionBuilder::emit_small_memcpy`](https://docs.rs/cranelift-frontend/0.51.0/cranelift_frontend/struct.FunctionBuilder.html#method.emit_small_memcpy) instead.

`get_libcall_funcref` is only used to legalize some float insts to libcalls:

https://github.com/bytecodealliance/cranelift/blob/6f4ff3153449600a5ad531b0622917c900f13c0d/cranelift-codegen/src/legalizer/libcall.rs#L10-L40

https://github.com/bytecodealliance/cranelift/blob/cabbacbe63477fcc7d1f1e36717d84f08f749a98/cranelift-codegen/src/ir/libcall.rs#L84-L102

**Comment by jyn514** [comment]
emit_small_memcpy is exactly what I was looking for, thanks :)

Would it be possible to make `get_libcall_funcref` a private method so other developers aren't confused in the future? (or `pub(crate)`
