### ISSUE TITLE
Post-branch instruction not fallthrough or jum

### ISSUE THREAD

**Issue by tathanhdinh** [bytecodealliance/cranelift#1280]
Hello all, I'm very new to `cranelift` so sorry if this question is trivial. 

I'm writing a toy `C` compiler using `cranelift` as backend. For the following function:

```c
int foo(int x) {
    int y;
    y = 7;
    if (x) {
        y = 3;
    }

    return y;
}
```

my compiler generates:

```
function u0:0(i32) -> i32 system_v {
ebb0(v0: i32):
    v1 = iconst.i32 0
    v2 = iconst.i32 7
    brz v0, ebb1(v2)
    v3 = iconst.i32 3
    jump ebb1(v3)

ebb1(v4: i32):
    return v4
}
```
but when I call `define_function` on the containing module, it crashes with error:

`Compilation(Verifier(VerifierErrors([VerifierError { location: inst3, context: Some("v3 = iconst.i32 3"), message: "post-branch instruction not fallthrough or jump" }])))', src/libcore/result.rs:1165:5`

I still do not understand why this occurs, many thanks for any feedback.

NB: I'm using `cranelift v.0.51.0`.

**Comment by iximeow** [comment]
hi! I don't think this is a cranelift bug, but is one of a few things. We switched to using basic blocks from extended basic blocks (written as "EBB"s in issues and cranelift source from time to time) a few months ago, and I think your function here would be valid under EBBs, but is not when using basic blocks.

in your clif function:
```
function u0:0(i32) -> i32 system_v {
ebb0(v0: i32):
    v1 = iconst.i32 0
    v2 = iconst.i32 7
    brz v0, ebb1(v2) <-- the branch the verifier error is talking about
    v3 = iconst.i32 3 <-- where your error occurs
    jump ebb1(v3)

ebb1(v4: i32):
    return v4
}
```

After a control flow operation the only thing cranelift allows under basic blocks is another control flow op (for "jump to foo else jump to bar" situations) or falling through to the next block.

If you really want to compile to cranelift IR using EBBs, I _think_ you can still do that by disabling the `basic-blocks` feature? I would recommend adjusting your compiler to produce basic blocks instead, something like:
```
function u0:0(i32) -> i32 system_v {
ebb0(v0: i32):
    v1 = iconst.i32 0
    v2 = iconst.i32 7
    brz v0, ebb2(v2)

ebb1:
    v3 = iconst.i32 3
    jump ebb2(v3)

ebb2(v4: i32):
    return v4
}
```
ought to work.

**Comment by tathanhdinh** [comment]
@iximeow thank you for the prompt answer.

I did follow the [`simplejit-demo`](https://github.com/bytecodealliance/simplejit-demo), and the compiler works for `cranelift 0.45.0` (but not for `0.51.0`).

> We switched to using basic blocks from extended basic blocks

I'm now understand the problem better, thank you for clarifying that and the proposed solution. I will change the compiler to work on basic blocks.
