### ISSUE TITLE
Tests broken on trunk

### ISSUE THREAD

**Issue by bnjbvr** [bytecodealliance/cranelift#1315]
Landing #1308 introduced new test failures, as caught by CI in both the pull request and on master. Please make sure that a PR passes CI *before* merging.

I will look at it quickly, and if the fix isn't obvious I'll immediately revert the patch.

cc @bjorn3 @sstangl

**Comment by bjorn3** [comment]
Sorry for the trouble, I hadn't noticed that there were test failures. It looks like those tests just need to be updated to use the correct recipe name.

**Comment by bnjbvr** [comment]
Fixed by #1316.
