### ISSUE TITLE
Cranelift generates ud2 instruction for f32 math

### ISSUE THREAD

**Issue by jyn514** [bytecodealliance/cranelift#946]
Consider the following CLIF:

```
function u0:0() -> i32 system_v {
    gv0 = symbol colocated u1:0  ; 2.5

ebb0:
    v0 = global_value.i64 gv0
    v1 = load.f32 v0
    v2 = f32const 0x1.000000p1
    v3 = fsub v1, v2
    v4 = fcvt_to_uint.i32 v3
    return v4
}
```

Cranelift generates the following object code when compiling for x86_64:

```
0000000000000600 <main>:
 600:   rex push %rbp
 602:   mov    %rsp,%rbp
 605:   lea    0xe8(%rip),%rax        # 6f4 <f>
 60c:   rex movss (%rax),%xmm0
 611:   rex mov $0x40000000,%eax
 617:   rex movd %eax,%xmm1
 61c:   rex subss %xmm1,%xmm0
 621:   rex mov $0x4f000000,%eax
 627:   rex movd %eax,%xmm1
 62c:   rex ucomiss %xmm1,%xmm0
 630:   rex jae 645 <main+0x45>
 633:   jnp    637 <main+0x37>
 635:   ud2    
... more assembly  ...
```

Note the `ud2` instruction, which will [crash the process with code 132](https://www.felixcloutier.com/x86/ud).

Expected behavior: executable exits with return code 0
Actual behavior: executable gets SIGILL and crashes during execution.

**Comment by bnjbvr** [comment]
That's the fcvt_to_uint that generates this ud2, and it's reached when the input can't be converted to an uint of the output type without loss of precision. You may use fcvt_to_uint_sat instead, to saturate the result in this case.

That being said, this ud2 is very tied to our needs in Firefox: extra metadata about the final instruction's offset is stored, and the runtime then installs a signal handler on ud2, and uses this to recover from ud2 being reached. Either you'd need to do something similar (I think wasmtime does this too), or we'd need to have another way to signal an error to the embedder.
