### ISSUE TITLE
cranelift-reader should have an option to error on pathological cases

### ISSUE THREAD

**Issue by bjorn3** [bytecodealliance/cranelift#951]
The following function will attempt to allocate 477777777 ebbs.

```
function %a(){
ebb477777777:
}
```

_Originally posted by @bjorn3 in https://github.com/CraneStation/cranelift/pull/944#issuecomment-525686450_

**Comment by bnjbvr** [comment]
Fixed by https://github.com/bytecodealliance/cranelift/commit/7cbf6e7d87b46e0a820369d1e69da4c2e986f701
