### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by bjorn3** [bytecodealliance/cranelift#963]
- What is the feature or code improvement you would like to do in Cranelift? Supporting native TLS.
- What is the value of adding this in Cranelift? This is required for https://github.com/bjorn3/rustc_codegen_cranelift/issues/388 (support multithreading in cg_clif)
- Do you have an implementation plan, and/or ideas for data structures or
  algorithms to use? Do the same thing as LLVM
- Have you considered alternative implementations? If so, how are they better
  or worse than your proposal?
    * Use a TLS base like Spidermonkey. That would make it impossible to interface with TLS variables created by LLVM or any other compiler which uses the native TLS facilities. It also wouldn't work when linking multiple objects together, as the native linker doesn't understand anything about it. Lastly it requires reserving a register, which won't work well when interfacing with C.

Edit: filled in new issue template

**Comment by bnjbvr** [comment]
Can you expand on which problem you're trying to solve, and what are the alternative implementations for this? (Bonus point if you fill in the feature issue template.)

Some questions that come to mind:

- We have an equivalent of TLS in Spidermonkey and never had the need for extra support here: most of TLS accesses are there done with loads/stores on the TLS base. Can you do the same in cg_clif?
- When one needs to resort to function calls, could user-facing function calls be used instead, and linking done by the embedder?

**Comment by bjorn3** [comment]
> Can you expand on which problem you're trying to solve, and what are the alternative implementations for this? (Bonus point if you fill in the feature issue template.)

Updated issue description.

> We have an equivalent of TLS in Spidermonkey and never had the need for extra support here: most of TLS accesses are there done with loads/stores on the TLS base. Can you do the same in cg_clif?

Responded in issue description.

> When one needs to resort to function calls, could user-facing function calls be used instead, and linking done by the embedder?

What do you mean? The `ElfTlsGetAddr` libcall is already translated to the right name by the module interface. It would not be possible to completely do this without modifying Cranelift, as the native TLS methods require you to store the result of a certain relocation in a certain register (impossible without Cranelift support), and then call a function to get the actual TLS pointer. It would be possible to only add the relocations support, but then actually calling the right function is just a few lines of extra code, while making it much easier to target any system from a frontend.
